---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-multiline-app
  namespace: infra-test
  labels:
    app: fluent-multiline-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-multiline-app
  template:
    metadata:
      labels:
        app: fluent-multiline-app
    spec:
      nodeSelector:
            kubernetes.io/hostname: xxxxxx
      containers:
        - name: fluent-multiline-go
          image: ricsanfre/fluent-multiline-app:go
          imagePullPolicy: IfNotPresent
        - name: fluent-multiline-java
          image: ricsanfre/fluent-multiline-app:java
          imagePullPolicy: IfNotPresent
